services:
  chatbot:
    build: .
    ports:
      - "8080:8080"
    command:
      - "streamlit"
      - "run"
      - "src/home.py"
      - "--server.port"
      - "8080"
    volumes:
      - ./src:/app/src
      - ./.streamlit:/app/.streamlit
      - ./.env:/app/.env
      - ./firebase-service-account.json:/app/firebase-service-account.json
      - ./firebase-google-oidc-client-secret.json:/app/firebase-google-oidc-client-secret.json
      - ./record_manager_cache.db:/app/record_manager_cache.db
