services:
  chatbot:
    build: .
    ports:
      - "8080:8080"
    command:
      - "streamlit"
      - "run"
      - "src/Home.py"
      - "--server.port"
      - "8080"
    volumes:
      - ./src:/app/src
      - ./.env:/app/.env
      - ./firebase-service-account.json:/app/firebase-service-account.json
